[tool.poetry]
name = "online_cinema"
version = "0.1.0"
description = ""
authors = ["Alona <alena.tsapenko7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">=0.116.1,<0.117.0"
uvicorn = { extras = ["standard"], version = ">=0.35.0,<0.36.0" }
sqlalchemy = ">=2.0.42,<3.0.0"
asyncpg = ">=0.30.0,<0.31.0"
alembic = ">=1.16.4,<2.0.0"
pydantic = { extras = ["email"], version = ">=2.11.7,<3.0.0" }
python-jose = { extras = ["cryptography"], version = ">=3.5.0,<4.0.0" }
passlib = { extras = ["bcrypt"], version = ">=1.7.4,<2.0.0" }
email-validator = ">=2.2.0,<3.0.0"
python-multipart = ">=0.0.20,<0.0.21"
aiofiles = ">=24.1.0,<25.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.17.0"
flake8 = "^7.3.0"
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"
httpx = "^0.28.1"
